apiVersion: sandia.gov/v1
kind: ThoriumCluster
metadata:
  name: dev
  namespace: thorium
spec:
  registry: "ghcr.io/cisagov/cisagov/thorium"
  version: "latest" 
  #registry_auth:
  #  "<registry.domain:port/path/to/thorium/image>": "REGISTRY_TOKEN"
  image_pull_policy: Always
  components:
    api:
      replicas: 1
      resources:
        cpu: 0
        memory: 0
      urls:
      - thorium.localhost
      ports:
      - 80
      - 443
    scaler:
      service_account: true
      resources:
        cpu: 0
        memory: 0
    #baremetal_scaler: {}
    search_streamer:
      resources:
        cpu: 0
        memory: 0
      cmd:
        - "/app/thorium-search-streamer"
      args:
        - "--config"
        - "/conf/thorium.yml"
        - "--keys"
        - "/keys/keys.yml"
        - "--workers"
        - "1"
    event_handler:
      resources:
        cpu: 0
        memory: 0
  config: 
    thorium:
      secret_key: "INSECURE_DEV_PASSWORD"
      tracing:
        external:
          Grpc:
            endpoint: "http://quickwit-indexer.quickwit.svc.cluster.local:7281"
            level: "Info"
        local:
          level: "Info"
      cors:
        insecure: true
      tags:
        partition_size: 3600
      files:
        bucket: "thorium-files"
        earliest: 1610596807
        partition_size: 3600
      repos:
        bucket: "thorium-repos"
        partition_size: 3600
      attachments:
        bucket: "thorium-attachments"
      results:
        bucket: "thorium-results"
        earliest: 1610596807
        partition_size: 3600
      ephemeral:
        bucket: "thorium-ephemeral"
      s3:
        access_key: "INSECURE_DEV_MINIO_ACCESS_KEY"
        secret_token: "INSECURE_DEV_MINIO_SECRET_KEY"
        endpoint: "http://minio.minio.svc.cluster.local:9000"
      auth:
      scaler:
        crane:
          insecure: true
        k8s:
          clusters:
            kubernetes-admin@cluster.local:
              alias: "dev"
              nodes:
                - "minikube"
    redis:
      host: "redis.redis.svc.cluster.local"
      port: 6379
      password: "INSECURE_DEV_PASSWORD"
    scylla:
      nodes:
        - "scylla-client.scylla.svc.cluster.local"
      replication: 1
      auth:
        username: "thorium"
        password: "INSECURE_DEV_PASSWORD"
    elastic:
      node: "https://elastic-es-http.elastic-system.svc.cluster.local:9200"
      username: "thorium"
      password: "INSECURE_DEV_PASSWORD"
      #results: "results"
